<?php
/**
 * @file
 * Contains hook and methods for the Stripe API module.
 */

use Drupal\Component\Serialization\Json;

/**
 * Implements hook_libraries_info().
 */
function stripe_api_libraries_info() {
  $libraries['stripe'] = [
    'name' => 'Stripe Payment API PHP Library',
    'vendor url' => 'https://github.com/stripe/stripe-php',
    'download url' => 'https://github.com/stripe/stripe-php/archive/master.zip',
    'version arguments' => [
      'file' => 'VERSION',
      'pattern' => '/([0-9a-zA-Z\.-]+)/',
      'lines' => 1,
    ],
    'files' => ['php' => ['init.php']],
    'callbacks' => ['post-load' => ['stripe_api_libraries_postload_callback']],
  ];
  return $libraries;
}

/**
 * Post-load callback for the Stripe PHP Library.
 *
 * @param array $library
 *   An array of library information.
 * @param string $version
 *   If the $library array belongs to a certain version, a string containing the
 *   version.
 * @param string $variant
 *   If the $library array belongs to a certain variant, a string containing the
 *   variant name.
 */
function stripe_api_libraries_postload_callback($library, $version = NULL, $variant = NULL) {
  if (!empty($library['loaded'])) {
    \Stripe\Stripe::setApiKey(_stripe_api_secret_key());
  }
}

/**
 * Returns the Stripe API secret key.
 *
 * @param string $mode
 *   Stripe mode, either 'live' or 'test'. Leave blank to use the active mode.
 *
 * @return string
 *   Returns the secret key.
 */
function _stripe_api_secret_key($mode = '') {
  $config = \Drupal::config('stripe_api.settings');
  if (!$mode) {
    $mode = $config->get('mode');
  }
  return $config->get($mode . '_secret_key');
}

/**
 * Returns the Stripe API public key.
 *
 * @param string $mode
 *   Stripe mode, either 'live' or 'test'. Leave blank to use the active mode.
 *
 * @return string
 *   Returns the public key.
 */
function _stripe_api_public_key($mode = '') {
  $config = \Drupal::config('stripe_api.settings');
  if (!$mode) {
    $mode = $config->get('mode');
  }
  return $config->get($mode . '_public_key');
}

/**
 * Makes a call to the Stripe API.
 *
 * @param string $obj
 *   Stripe object. Can be a Charge, Refund, Customer, Subscription, Card, Plan,
 *   Coupon, Discount, Invoice, InvoiceItem, Dispute, Transfer, TransferReversal,
 *   Recipient, BankAccount, ApplicationFee, FeeRefund, Account, Balance, Event,
 *   Token, BitcoinReceiver, FileUpload.
 *
 * @param string $method
 *   Stripe object method. Common operations include retrieve, all, create,
 *
 * @param mixed $params
 *   Additional params to pass to the method. Can be an array, string.
 *
 * @return Stripe\ApiResource
 *   Returns the ApiResource or NULL on error.
 */
function stripe_api_call($obj, $method = NULL, $params = NULL) {
  libraries_load('stripe');
  $obj = ucfirst($obj);
  $class = '\\Stripe\\' . $obj;
  if ($method) {
    try {
      return call_user_func([$class, $method], $params);
    } catch (Exception $e) {
      \Drupal::logger('stripe_api')->error('Error: @error <br /> @args', [
        '@args' => Json::encode([
          'object' => $obj,
          'method' => $method,
          'params' => $params,
        ]),
        '@error' => $e->getMessage(),
      ]);
      return NULL;
    }
  }
  return $class;
}
